---
title: Weekly Highlights - Brazil
subtitle: WEEK `r if( lubridate::isoweek(lubridate::today()) == 1) {52} else { lubridate::isoweek(lubridate::today())}  `/`r lubridate::year(lubridate::today())`
date: Weekly Highlights - Brazil
author:
  - name: Chiara Orsini and Vivianne Barbosa Soares
    affiliation: Associate Donor Relations Officer and Senior Reporting Assistant
    email: barbosas@unhcr.org

output:
  pagedown::html_paged:
    # put the path to your cover image
    front_cover: cover_grey.svg
    css: resources/paged.css
    includes:
        after_body: resources/back_paged.html
# Set  toc title, default none
toc-title: Contents
# Change to true to include list of tables
lot: false
# Set lot title, default: "List of Tables"
lot-title: "Tables"
# Change to true to include list of figures
lof: false
# Set lof title, default: "List of Figures"
lof-title: "Figures"
# If you include any <abbr> a list of abbreviations will be built.
# Set lof title, default: "List of Abbreviations"
loa-title: "Acronyms"
paged-footnotes: true
links-to-footnotes: true
# uncomment this line to produce HTML and PDF in RStudio:
# knit: pagedown::chrome_print
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.retina = 2,
                      fig.showtext = TRUE,
                      dev = "ragg_png",
                      dpi = 300)

## Basic todyverse packages
##install.packages("tidyverse")
##install.packages("lubridate")
##install.packages("httr")

## Package for UNHCR report template
##install.packages("devtools")
##devtools::install_github("vidonne/unhcrdown")

## Package to create automatation with http://rstudio.unhcr.org
##devtools::install_github("rstudio/rsconnect")


library(tidyverse)
library(lubridate)
library(httr)
library(ragg)
library(showtext)
library(unhcrdesign)

rsconnect::writeManifest
rsconnect::writeManifest(appPrimaryDoc = "report.Rmd")

#knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

```{r data}
data <-
  GET("https://kobo.unhcr.org/api/v2/assets/a5BzV4z9cA3kx8y9hFEUG7/data.json",
      add_headers(Authorization = glue::glue("Token {Sys.getenv('KOBO_API_KEY')}"))) %>% 
  content(as = "text") %>% 
  jsonlite::fromJSON() %>% 
  pluck("results") %>% 
  as_tibble()
data <- 
  data %>% 
  select(id = `_id`,
         year = `_submission_time`,
         week = `group_dv7hn13/Week_of_Reporting`,
         office_unit = `group_dv7hn13/Office_Unit`,
         reporting_unit = `In_which_Unit_do_you_have_some`,
         
         work_operation.narrative = `group_hx2aq27/NON_CONFIDENTIAL_PR_UNHCR_WORK_OPERATION`,
         work_operation.confidential = `group_hx2aq27/CONFIDENTIAL_PROVID_UNHCR_WORK_OPERATION`,
         
         new_trends.narrative = `group_gt36y03/NON_CONFIDENTIAL_PR_FOCUS_ON_NEW_TRENDS`,
         
         protection.narrative = `group_xi4iq21/NON_CONFIDENTIAL_Pl_rotection_activities`,
         protection.confidential = `group_xi4iq21/CONFIDENTIAL_Please_rotection_activities`,
         
         indigenous.narrative = `group_yz3lf65/NON_CONFIDENTIAL_Pl_n_indigenous_peoples`,
         indigenous.confidential = `group_yz3lf65/CONFIDENTIAL_Please_n_indigenous_peoples`,
         
         pathways.narrative = `group_lo0ux27/NON_CONFIDENTIAL_Pl_omplemetary_pathways`,
         pathways.confidential = `group_lo0ux27/CONFIDENTIAL_Please_omplemetary_pathways`,
         
         shelter.narrative = `group_so4kv20/NON_CONFIDENTIAL_Pl_o_emergency_shelters`,
         shelter.confidential = `group_so4kv20/CONFIDENTIAL_Please_o_emergency_shelters`,
         
         relocation.narrative = `group_ne27d45/NON_CONFIDENTIAL_Pl_elocation_activities`,
         livelihoods.narrative = `group_ne27d45/NON_CONFIDENTIAL_Pl_velihoods_activities`,
         livelihoods.confidential = `group_ne27d45/CONFIDENTIAL_Please_velihoods_activities`,
         
         cbi.narrative = `group_wp7sb17/NON_CONFIDENTIAL_Pl_rt_on_CBI_activities`)


data <- 
  data %>% 
  mutate(year = year(year),
         week = parse_number(week)) %>%
  pivot_longer(-c(id, year, week, office_unit), names_pattern = "(.+)\\.(.+)", names_to = c("section", "dimension")) %>% 
  pivot_wider(names_from = "dimension", values_from = "value")


data <- 
  data %>% 
  mutate(office_unit = case_when(office_unit == "so_boa_vista" ~ "SO Boa Vista",
                             office_unit == "livelihoods___bras_lia" ~ "Livelihoods - Brasília",
                             office_unit == "protection___bras_lia" ~ "Protection - Brasília",
                             office_unit == "resettlement_and_complementary_paths___b" ~ "Resettlement and Complementary Pathways",
                             office_unit == "indigenous___bras_lia" ~ "Indigenous – Brasília",
                             office_unit == "cbi___bras_lia" ~ "CBI – Brasília ",
                             office_unit == "psp___s_o_paulo" ~ "PSP – São Paulo",
                             office_unit == "fo_s_o_paulo" ~ "FO São Paulo",
                             office_unit == "fp_bel_m" ~ "FU Belém",
                             office_unit == "fo_manaus" ~ "FO Manaus",
                             office_unit == "fu_pacaraima" ~ "FU Pacaraima"),
         section = c(work_operation = "Context + Situation", 
                      new_trends = "Population Trends", 
                      protection = "Protection",
                      indigenous = "Indigenous Peoples", 
                      pathways = "Resettlement and Complementary Pathways", 
                      shelter = "Shelter",
                      relocation = "Internal Relocation",
                      livelihoods = "Livelihoods",
                      cbi = "CBI")[section],
         narrative = replace_na(narrative, "Nothing to report."))


data <- 
  data %>% 
  mutate(office_unit = factor(office_unit),
         section = factor(section, levels = c("Context + Situation", "Population Trends", "Protection", "Indigenous Peoples", "Resettlement and Complementary Pathways", "Shelter", "Internal Relocation", "Livelihoods", "CBI")))


data <- 
  data %>% 
  select(id, year, week, office_unit, section, narrative, confidential) %>%
  filter(!is.na(section))

```


```{r datafilter}
## If generated for report happening after this current week
# isoweek(ymd("2012-03-26"))
if(isoweek(today()) == 1 ) {
  ## If generated for report happening this current week
  datanow <- data %>% filter(year == (isoyear(today()) ), week == 52)
} else {
  datanow <- data %>% filter(year == isoyear(today()), week == isoweek(today()))
}
## Clean duplicated... dangerous
# datanow2 <- datanow|>
#            group_by(country, section) |>
#             filter(duplicated(country, section) | n()==1) |>
#             ungroup()
```

```{r renderers}
render_section <- function(datanow, section) {
  cat(glue::glue("### {section}"), sep = "\n")
  datanow <- data %>% filter(section == section)
  if (any(!is.na(datanow$confidential) & datanow$confidential == "yes"))
    cat("<strong style='color: #EF4A60'>CONFIDENTIAL</strong>", sep = "\n")
  cat("\n")
  cat(datanow$narrative, sep = "\n")
  cat("\n")
}
render_office_unit <- function(datanow, office_unit) {
  cat(glue::glue("## {.office.unit}"), sep = "\n")
  datanow <- datanow %>% filter(office_unit == office_unit)
  walk(levels(fct_drop(datanow$section)), ~render_section(datanow, .))
}
```

